apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: surrealdb
  repo: https://helm.surrealdb.com
  version: 0.4.0
  namespace: myapp
  releaseName: dev
  valuesFile: surrealdb-values.yaml

namespace: myapp

resources:
- deployment.yaml
- service.yaml
